"""
Example: RAG pre-processing pipeline (Python)
Compress → chunk → rerank → pack into context window
"""

from utilix.tools.ai_agent import (
    compress_html,
    compress_markdown,
    chunk_text,
    estimate_tokens,
    trim_to_tokens,
    rerank_chunks,
    score_relevance,
    expand_query,
    extract_keywords,
    summarize_for_llm,
)

CONTEXT_BUDGET = 6000  # tokens for retrieved context

# --- Step 1: Compress raw HTML from a web scrape ---
def preprocess_page(raw_html: str) -> str:
    result = compress_html(
        raw_html,
        remove_scripts=True,
        remove_styles=True,
        remove_comments=True,
        collapse_whitespace=True,
    )
    before = result["originalBytes"]
    after = result["compressedBytes"]
    print(f"HTML: {before}B → {after}B ({result['savingsPct']:.0f}% saved)")
    return result["html"]


# --- Step 2: Chunk for embedding ---
def chunk_for_embedding(text: str, max_tokens: int = 256, overlap: int = 32) -> list[str]:
    result = chunk_text(text, max_tokens=max_tokens, overlap=overlap, strategy="sentence")
    chunks = [c["text"] for c in result["chunks"]]
    print(f"Produced {len(chunks)} chunks ({result['totalTokens']} total tokens)")
    return chunks


# --- Step 3: Query expansion for better retrieval ---
def expand_and_retrieve(query: str, chunks: list[str], top_k: int = 5) -> list[dict]:
    # Expand query with synonyms/variants for better recall
    expanded = expand_query(query)
    all_variants = [query] + expanded["variants"]
    print(f"Query expanded: {len(all_variants)} variants")

    # Score each chunk against all query variants, take max
    scored = []
    for chunk in chunks:
        max_score = max(
            score_relevance(variant, chunk)["score"]
            for variant in all_variants
        )
        scored.append({"chunk": chunk, "score": max_score})

    # Re-rank and return top-K
    scored.sort(key=lambda x: x["score"], reverse=True)
    return scored[:top_k]


# --- Step 4: Pack chunks into context budget ---
def pack_context(ranked: list[dict], budget: int) -> str:
    parts = [item["chunk"] for item in ranked]
    joined = "\n\n---\n\n".join(parts)

    est = estimate_tokens(joined)
    if est["tokens"] <= budget:
        return joined

    trimmed = trim_to_tokens(joined, max_tokens=budget, strategy="end")
    return trimmed["text"]


# --- Demo ---
raw_html = """
<html>
<head>
  <script>analytics()</script>
  <style>body{color:red}</style>
</head>
<body>
  <nav>Home | Docs | Blog</nav>
  <article>
    <h1>Vector Databases Explained</h1>
    <p>A vector database stores high-dimensional embeddings generated by ML models.
    Unlike relational databases, they enable similarity search — finding semantically
    similar content rather than exact matches.</p>
    <p>Core operation: K-nearest neighbor (KNN) search using ANN algorithms like HNSW,
    IVF-Flat, or FAISS. These trade a small recall penalty for dramatic speed gains.</p>
    <p>Common products: Pinecone (managed), Weaviate (open-source, multi-modal),
    Qdrant (Rust, high perf), Chroma (local dev), pgvector (Postgres extension).</p>
    <p>For RAG pipelines, vector DBs serve as long-term memory: documents are chunked,
    embedded, and stored at index time. At query time, the top-K chunks are injected
    into the LLM context as grounding information.</p>
  </article>
  <footer>© 2024 Example</footer>
</body>
</html>
"""

# Full pipeline
clean_text = preprocess_page(raw_html)
chunks = chunk_for_embedding(clean_text, max_tokens=100, overlap=15)

query = "what algorithms do vector databases use for similarity search?"
top_chunks = expand_and_retrieve(query, chunks, top_k=3)

context = pack_context(top_chunks, CONTEXT_BUDGET)
final_tokens = estimate_tokens(context)["tokens"]
print(f"\nContext ready: {final_tokens} tokens, {len(top_chunks)} chunks")

# Optional: summarize if still too long
if final_tokens > 2000:
    summary = summarize_for_llm(context, max_tokens=500, strategy="extractive")
    print(f"Summarized to {estimate_tokens(summary['summary'])['tokens']} tokens")
    context = summary["summary"]

# Extract keywords for metadata/tagging
keywords = extract_keywords(clean_text, top_n=8)
print("\nTop keywords:", [k["word"] for k in keywords["keywords"]])
print("\n--- Final context ---")
print(context)
