/**
 * Example: Context compression — shrink inputs before sending to an LLM
 * Useful when you're over the token limit or want to reduce API costs.
 */

import {
  compressHtml,
  compressMarkdown,
  compressJson,
  summarizeForLlm,
  trimToTokens,
  estimateTokens,
} from '@utilix-tech/sdk/ai_agent'

const TOKEN_LIMIT = 4000

function logCompression(label: string, before: number, after: number) {
  const saved = ((1 - after / before) * 100).toFixed(0)
  console.log(`[${label}] ${before} → ${after} tokens (${saved}% saved)`)
}

// --- HTML page from a web scrape ---
const rawHtml = `
<!DOCTYPE html>
<html>
<head>
  <script src="analytics.js"></script>
  <script>window.dataLayer = []</script>
  <style>body { font-family: sans-serif; color: #333; } nav { background: #eee; }</style>
  <link rel="stylesheet" href="theme.css">
</head>
<body>
  <nav><ul><li>Home</li><li>Docs</li><li>Blog</li></ul></nav>
  <main>
    <h1>Getting Started with Utilix</h1>
    <p>Utilix provides 130+ developer utility tools available as a web app, REST API, Node.js SDK, Python SDK, and MCP server.</p>
    <p>All tools are deterministic — no LLM calls, no side effects. You can use them locally or call the hosted API.</p>
    <section>
      <h2>AI Agent Tools</h2>
      <p>The AI agent module includes 28 tools built specifically for LLM pipelines: token estimation, context compression, PII detection, structured extraction, RAG utilities, and JSON diffing.</p>
    </section>
  </main>
  <footer><p>© 2024 Utilix · Privacy · Terms</p></footer>
</body>
</html>
`

const htmlResult = compressHtml(rawHtml, { removeScripts: true, removeStyles: true, collapseWhitespace: true })
const htmlBefore = estimateTokens(rawHtml).tokens
const htmlAfter = estimateTokens(htmlResult.html).tokens
logCompression('HTML', htmlBefore, htmlAfter)

// --- Markdown documentation ---
const rawMarkdown = `
---
title: Utilix SDK Reference
author: Utilix Team
date: 2024-01-15
tags: [sdk, reference, node, python]
---

# Utilix SDK Reference



## Installation

### Node.js

\`\`\`bash
npm install @utilix-tech/sdk
\`\`\`

### Python

\`\`\`bash
pip install utilix-sdk
\`\`\`



## Quick Start

Import and call any tool directly.   No configuration needed.   All tools are synchronous.


`

const mdResult = compressMarkdown(rawMarkdown, { removeFrontmatter: true, collapseBlankLines: true, trimLines: true })
const mdBefore = estimateTokens(rawMarkdown).tokens
const mdAfter = estimateTokens(mdResult.markdown).tokens
logCompression('Markdown', mdBefore, mdAfter)

// --- JSON API response ---
const rawJson = JSON.stringify({
  status: 'ok',
  requestId: 'req_abc123',
  timestamp: '2024-01-15T10:00:00Z',
  data: {
    users: [
      { id: 1, name: 'Alice', email: 'alice@example.com', deletedAt: null, metadata: {}, tags: [] },
      { id: 2, name: 'Bob', email: 'bob@example.com', deletedAt: null, metadata: {}, tags: [] },
    ],
    pagination: { page: 1, perPage: 20, total: 2, nextPage: null, prevPage: null },
    _debug: { queryTime: 12, cacheHit: true, region: 'us-east-1' },
  },
})

const jsonResult = compressJson(rawJson, { removeNulls: true, removeEmptyArrays: true, removeEmptyObjects: true, removeKeys: ['_debug', 'requestId', 'timestamp'] })
const jsonBefore = estimateTokens(rawJson).tokens
const jsonAfter = estimateTokens(jsonResult.json).tokens
logCompression('JSON', jsonBefore, jsonAfter)

// --- Long article that needs extractive summary ---
const longArticle = `
Vector databases have emerged as a critical infrastructure component for AI applications.
Unlike traditional relational databases, vector databases are optimized for storing and
querying high-dimensional embedding vectors. These vectors are numerical representations
of unstructured data like text, images, and audio, generated by machine learning models.

The core operation in a vector database is similarity search: given a query vector, find
the K nearest vectors in the database. This is called K-nearest neighbor (KNN) search.
Because exact KNN search is O(n·d) — where n is the number of vectors and d is the
dimensionality — it becomes impractical at scale. Vector databases use approximate nearest
neighbor (ANN) algorithms to trade a small amount of recall for massive speedups.

Common ANN algorithms include HNSW (Hierarchical Navigable Small World graphs),
IVF-Flat (Inverted File Index), and FAISS (Facebook AI Similarity Search).
HNSW builds a multi-layer graph where each layer is a subset of the full index,
enabling logarithmic-time search. IVF-Flat clusters vectors into Voronoi cells and
only searches the cells nearest to the query.

Popular vector database products include Pinecone (managed cloud), Weaviate (open-source,
multi-modal), Qdrant (Rust-based, high performance), Chroma (lightweight, great for
local development), and pgvector (Postgres extension for teams already on Postgres).

For RAG (Retrieval Augmented Generation) pipelines, vector databases serve as the
long-term memory for LLMs. Documents are chunked, embedded, and stored at index time.
At query time, the user query is embedded and the top-K most similar chunks are retrieved
and injected into the LLM context window as grounding information.
`

const summary = summarizeForLlm(longArticle, { maxTokens: 80, strategy: 'extractive' })
const sumBefore = estimateTokens(longArticle).tokens
const sumAfter = estimateTokens(summary.summary).tokens
logCompression('Summary', sumBefore, sumAfter)
console.log('\nSummary:\n' + summary.summary)

// --- Final trim if still over budget ---
const combined = [htmlResult.html, mdResult.markdown, jsonResult.json, summary.summary].join('\n\n')
const combinedTokens = estimateTokens(combined).tokens
console.log(`\nCombined: ${combinedTokens} tokens`)

if (combinedTokens > TOKEN_LIMIT) {
  const trimmed = trimToTokens(combined, { maxTokens: TOKEN_LIMIT, strategy: 'middle' })
  console.log(`Trimmed to budget: ${estimateTokens(trimmed.text).tokens} tokens`)
}
