/**
 * Example: Context compression — shrink inputs before sending to an LLM
 * Useful when you're over the token limit or want to reduce API costs.
 */

import {
  compressHtml,
  compressMarkdown,
  compressJson,
  summarizeForLlm,
  trimToTokens,
  estimateTokens,
} from '@utilix-tech/sdk/ai_agent'

const TOKEN_LIMIT = 4000

function logCompression(label: string, before: number, after: number) {
  const saved = ((1 - after / before) * 100).toFixed(0)
  console.log(`[${label}] ${before} → ${after} tokens (${saved}% saved)`)
}

// --- HTML page from a web scrape ---
const rawHtml = `
<!DOCTYPE html>
<html>
<head>
  <script src="analytics.js"></script>
  <script>window.dataLayer = []</script>
  <style>body { font-family: sans-serif; color: #333; } nav { background: #eee; }</style>
</head>
<body>
  <nav><ul><li>Home</li><li>Docs</li><li>Blog</li></ul></nav>
  <main>
    <h1>Getting Started with Utilix</h1>
    <p>Utilix provides 130+ developer utility tools available as a web app, REST API, Node.js SDK, Python SDK, and MCP server.</p>
    <p>All tools are deterministic — no LLM calls, no side effects. You can use them locally or call the hosted API.</p>
    <section>
      <h2>AI Agent Tools</h2>
      <p>The AI agent module includes 28 tools for LLM pipelines: token estimation, context compression, PII detection, extraction, RAG, and JSON diffing.</p>
    </section>
  </main>
  <footer><p>© 2024 Utilix</p></footer>
</body>
</html>
`

// .compressed holds the cleaned HTML string
const htmlResult = compressHtml(rawHtml, { removeScripts: true, removeStyles: true, collapseWhitespace: true })
const htmlBefore = estimateTokens(rawHtml).tokens
const htmlAfter = estimateTokens(htmlResult.compressed).tokens
logCompression('HTML', htmlBefore, htmlAfter)

// --- Markdown documentation ---
const rawMarkdown = `
---
title: Utilix SDK Reference
author: Utilix Team
tags: [sdk, reference]
---

# Utilix SDK Reference



## Installation

\`\`\`bash
npm install @utilix-tech/sdk
\`\`\`



## Quick Start

Import and call any tool directly.   No configuration needed.   All tools are synchronous.


`

// opts use camelCase — stripFrontmatter (not removeFrontmatter)
const mdResult = compressMarkdown(rawMarkdown, { stripFrontmatter: true, collapseBlankLines: true, trimLines: true })
const mdBefore = estimateTokens(rawMarkdown).tokens
const mdAfter = estimateTokens(mdResult.compressed).tokens
logCompression('Markdown', mdBefore, mdAfter)

// --- JSON API response (pass object, not string) ---
const rawObj = {
  status: 'ok',
  requestId: 'req_abc123',
  data: {
    users: [
      { id: 1, name: 'Alice', deletedAt: null, metadata: {}, tags: [] },
      { id: 2, name: 'Bob',   deletedAt: null, metadata: {}, tags: [] },
    ],
    pagination: { page: 1, perPage: 20, total: 2, nextPage: null, prevPage: null },
  },
}

const jsonResult = compressJson(rawObj, { removeNulls: true, removeEmptyArrays: true, removeEmptyObjects: true })
const jsonBefore = estimateTokens(JSON.stringify(rawObj)).tokens
const jsonAfter = estimateTokens(jsonResult.compressed).tokens
logCompression('JSON', jsonBefore, jsonAfter)

// --- Long article → extractive summary ---
const longArticle = `
Vector databases have emerged as a critical infrastructure component for AI applications.
Unlike traditional relational databases, vector databases are optimized for storing and
querying high-dimensional embedding vectors generated by machine learning models.

The core operation is similarity search: given a query vector, find the K nearest vectors.
Because exact KNN is O(n·d), vector databases use approximate nearest neighbor (ANN)
algorithms like HNSW, IVF-Flat, or FAISS to trade a small recall penalty for speed.

Popular products: Pinecone (managed cloud), Weaviate (open-source, multi-modal),
Qdrant (Rust-based, high performance), Chroma (local dev), pgvector (Postgres extension).

For RAG pipelines, vector databases serve as long-term LLM memory. Documents are chunked,
embedded, and stored at index time. At query time, the top-K similar chunks are retrieved
and injected into the LLM context as grounding information.
`

// positional params: summarizeForLlm(text, maxTokens, strategy)
const summary = summarizeForLlm(longArticle, 80, 'extractive')
const sumBefore = estimateTokens(longArticle).tokens
const sumAfter = estimateTokens(summary.summary).tokens
logCompression('Summary', sumBefore, sumAfter)
console.log('\nSummary:\n' + summary.summary)

// --- Combine and trim to final budget ---
const combined = [htmlResult.compressed, mdResult.compressed, jsonResult.compressed, summary.summary].join('\n\n')
const combinedTokens = estimateTokens(combined).tokens
console.log(`\nCombined: ${combinedTokens} tokens`)

if (combinedTokens > TOKEN_LIMIT) {
  // positional params: trimToTokens(text, maxTokens, strategy)
  const trimmed = trimToTokens(combined, TOKEN_LIMIT, 'middle')
  console.log(`Trimmed to budget: ${estimateTokens(trimmed.trimmed).tokens} tokens`)
}
